### ISSUE TITLE
Doesn't work with ruby 2.0.0

### ISSUE THREAD

**Issue by chrismytton** [everypolitician/scraped_page_archive#28]
When trying to use `ScrapedPageArchive#open_from_archive` on Ruby 2.0.0-p353 I get the following error:

```
/Users/chris/.rbenv/versions/2.0.0-p353/lib/ruby/2.0.0/open-uri.rb:474:in `=~': no implicit conversion of Array into String (TypeError)
        from /Users/chris/.rbenv/versions/2.0.0-p353/lib/ruby/2.0.0/open-uri.rb:474:in `content_type_parse'
        from /Users/chris/.rbenv/versions/2.0.0-p353/lib/ruby/2.0.0/open-uri.rb:509:in `charset'
        from /Users/chris/.rbenv/versions/2.0.0-p353/lib/ruby/2.0.0/open-uri.rb:431:in `meta_setup_encoding'
        from /Users/chris/.rbenv/versions/2.0.0-p353/lib/ruby/2.0.0/open-uri.rb:452:in `meta_add_field'
        from /Users/chris/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/scraped_page_archive-0.4.0/lib/scraped_page_archive.rb:68:in `block (2 levels) in response_from'
        from /Users/chris/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/scraped_page_archive-0.4.0/lib/scraped_page_archive.rb:68:in `each'
        from /Users/chris/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/scraped_page_archive-0.4.0/lib/scraped_page_archive.rb:68:in `block in response_from'
        from /Users/chris/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/scraped_page_archive-0.4.0/lib/scraped_page_archive.rb:66:in `tap'
        from /Users/chris/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/scraped_page_archive-0.4.0/lib/scraped_page_archive.rb:66:in `response_from'
        from /Users/chris/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/scraped_page_archive-0.4.0/lib/scraped_page_archive.rb:57:in `block in open_from_archive'
        from /Users/chris/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/git-1.3.0/lib/git/base.rb:106:in `block in chdir'
        from /Users/chris/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/git-1.3.0/lib/git/base.rb:105:in `chdir'
        from /Users/chris/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/git-1.3.0/lib/git/base.rb:105:in `chdir'
        from /Users/chris/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/scraped_page_archive-0.4.0/lib/scraped_page_archive.rb:50:in `open_from_archive'
        from scraper.rb:20:in `noko_for'
        from scraper.rb:31:in `scrape_list'
        from scraper.rb:120:in `<main>'
```

It looks like this is because Ruby 2.0.0 doesn't handle multi-value header fields in the same way newer versions do, so we need to manually concatenate the headers together.

**Comment by chrismytton** [comment]
This error was seen when trying to run https://github.com/everypolitician-scrapers/kenya-mzalendo/pull/3.

**Comment by chrismytton** [comment]
Fixes in https://github.com/everypolitician/scraped_page_archive/pull/29
